version: '3'
services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://postgres@psql/services
    volumes:
      - ./:/app
    depends_on:
      - psql
  psql:
    image: "postgres:latest"
    ports:
      - "5432"
